tup = (10,20,30,40)
print(len(tup))
tup = tup+(50,10,)
tup = tup+(70,)
print(len(tup))
print(tup[0])
print(tup.count(10))
print(tup)
print(tup.index(10))
lis = list(tup)
lis.reverse()
tup = tuple(lis)
print(tup)
print(tup.index(10))